[package]
name = "vslam-sandbox"
version = "0.1.0"
authors = ["Geordon Worley <vadixidav@gmail.com>"]
edition = "2018"

[dependencies]
cv = { version = "0.6.0", path = "../cv" }
cv-reconstruction = { version = "0.1.0", path = "../cv-reconstruction", features = ["serde-serialize"] }
structopt = "0.3.15"
serde = { version = "1.0.114", features = ["derive"] }
image = "0.23.7"
rand = "0.7.3"
rand_pcg = "0.2.1"
log = "0.4.11"
pretty_env_logger = "0.4.0"
ply-rs = "0.1.2"
float-ord = "0.2.0"
levenberg-marquardt = "0.5.2"
slab = "0.4.2"
ahash = "0.4.3"
maplit = "1.0.2"
space = "0.10.3"
argmin = "0.3.1"
ndarray = "0.13.1"
itertools = "0.9.0"
imageproc = "0.21.0"
conv = "0.3.3"
hnsw = { version = "0.6.1", features = ["serde1"] }
bincode = "1.3.1"
serde_json = "1.0.57"
